"""
Test Battery for Kinetic Subtitles, Levenshtein Forced Alignment & Modern HUD
=============================================================================
Verifies:
1. Levenshtein edit distance and phonetic normalization.
2. Forced alignment with complete elimination of ASR hallucinations.
3. Linear timestamp interpolation for unaligned words.
4. ASS, SRT, VTT, and JSON manifest generation.
5. 4K/1080p HUD overlay generation and alpha transparency.
6. SubtitlesAdapter integration within the VideoPro orchestration system.
"""

import sys
import json
import unittest
from pathlib import Path

# Add project root to sys.path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from PIL import Image

from app.core.subtitles.forced_aligner import (
    LevenshteinForcedAligner,
    CanonicalToken,
    ASRWord,
    normalize_token,
    levenshtein_distance,
    token_similarity
)
from app.core.subtitles.kinetic_styler import (
    KineticSubtitleStyler,
    SubtitleChunk,
    SubtitleWord
)
from app.core.subtitles.hud_generator import ModernHUDGenerator
from app.core.orchestration.adapters.subtitles_adapter import SubtitlesAdapter
from app.core.orchestration.job import JobStep


def test_token_normalization_and_similarity():
    """Test unicode stripping, diacritics, and similarity scoring."""
    assert normalize_token("¡CUÁNTICO!") == "cuantico"
    assert normalize_token("¿Quién?") == "quien"
    assert normalize_token("10^-9") == "109"

    # Exact similarity after normalization
    assert token_similarity("Cuántico", "cuantico") == 1.0
    assert token_similarity("silicio", "silicio") == 1.0

    # Minor typo tolerance
    sim_typo = token_similarity("procesador", "proceador")
    assert sim_typo > 0.80

    # Prefix match
    sim_prefix = token_similarity("cuántico", "cuántic")
    assert sim_prefix >= 0.80


def test_forced_alignment_purges_hallucinations():
    """
    Test that ASR hallucinations (extra words generated by Whisper)
    are purged and canonical text is 100% preserved.
    """
    script = "En este instante a doscientos setenta y tres grados bajo cero la física clásica acaba de romperse."
    
    # Simulate Whisper output with 1 typo, 1 missing word ("y"), and 3 hallucinated filler words at the end
    asr_data = [
        {"word": "En", "start": 0.5, "end": 0.7},
        {"word": "este", "start": 0.72, "end": 0.95},
        {"word": "instante", "start": 1.0, "end": 1.45},
        {"word": "a", "start": 1.5, "end": 1.65},
        {"word": "doscientos", "start": 1.7, "end": 2.2},
        {"word": "setenta", "start": 2.25, "end": 2.6},
        # "y" is omitted by ASR
        {"word": "trez", "start": 2.65, "end": 2.9},  # typo
        {"word": "grados", "start": 2.95, "end": 3.3},
        {"word": "bajo", "start": 3.35, "end": 3.6},
        {"word": "cero", "start": 3.65, "end": 4.0},
        {"word": "la", "start": 4.1, "end": 4.25},
        {"word": "física", "start": 4.3, "end": 4.65},
        {"word": "clásica", "start": 4.7, "end": 5.1},
        {"word": "acaba", "start": 5.15, "end": 5.45},
        {"word": "de", "start": 5.5, "end": 5.65},
        {"word": "romperse", "start": 5.7, "end": 6.2},
        # Hallucinations produced in silence:
        {"word": "[Música]", "start": 6.5, "end": 7.0},
        {"word": "Subtítulos", "start": 7.1, "end": 7.5},
        {"word": "Comunidad", "start": 7.6, "end": 8.0}
    ]

    aligner = LevenshteinForcedAligner()
    result = aligner.align(script, asr_data, total_audio_duration=10.0)

    # 1. Total canonical words must match script exactly
    expected_words = script.split()
    assert result.total_canonical_words == len(expected_words)
    aligned_text = " ".join(t.word for t in result.aligned_tokens)
    assert aligned_text == script

    # 2. Hallucinations must be dropped
    assert result.hallucinated_asr_dropped >= 3

    # 3. Missing word "y" must be interpolated smoothly with valid monotonic timestamps
    y_token = next(t for t in result.aligned_tokens if t.word == "y")
    assert y_token.start is not None
    assert y_token.end is not None
    assert y_token.start < y_token.end

    # 4. Strict monotonicity across all tokens
    for i in range(len(result.aligned_tokens) - 1):
        curr_tok = result.aligned_tokens[i]
        next_tok = result.aligned_tokens[i + 1]
        assert curr_tok.start < curr_tok.end
        assert curr_tok.end <= next_tok.start or (next_tok.start >= curr_tok.start)


def test_kinetic_styler_ass_generation():
    """Verify ASS formatting, styles, colors, and Karaoke tags."""
    styler = KineticSubtitleStyler(
        target_resolution="4k",
        highlight_color_hex="#FFD700",
        text_color_hex="#FFFFFF"
    )

    tokens = [
        CanonicalToken(word="En", clean_word="en", start=0.5, end=0.7, shot_index=1),
        CanonicalToken(word="este", clean_word="este", start=0.75, end=1.0, shot_index=1),
        CanonicalToken(word="instante,", clean_word="instante", start=1.05, end=1.5, is_key_word=True, shot_index=1),
        CanonicalToken(word="a", clean_word="a", start=1.55, end=1.7, shot_index=1),
        CanonicalToken(word="cero.", clean_word="cero", start=1.75, end=2.2, is_key_word=True, shot_index=1)
    ]

    chunks = styler.build_chunks(tokens)
    assert len(chunks) >= 1

    ass_text = styler.generate_ass(chunks, title="Test Suite")
    assert "[Script Info]" in ass_text
    assert "PlayResX: 3840" in ass_text
    assert "PlayResY: 2160" in ass_text
    assert "Style: VoxKinetic" in ass_text
    assert "&H0000D7FF&" in ass_text  # ASS BGR for #FFD700 Gold
    assert "\\k" in ass_text  # Karaoke tags present
    assert "Dialogue:" in ass_text


def test_srt_and_json_manifest_exports(tmp_path):
    """Verify SRT, VTT, and JSON manifest generation."""
    styler = KineticSubtitleStyler(target_resolution="1080p")
    tokens = [
        CanonicalToken(word="Un", clean_word="un", start=0.0, end=0.3, shot_index=1),
        CanonicalToken(word="procesador", clean_word="procesador", start=0.35, end=0.9, is_key_word=True, shot_index=1),
        CanonicalToken(word="atómico.", clean_word="atomico", start=0.95, end=1.5, is_key_word=True, shot_index=1)
    ]
    chunks = styler.build_chunks(tokens)

    srt_text = styler.generate_srt(chunks)
    assert "00:00:00,000 --> 00:00:01,500" in srt_text
    assert "PROCESADOR" in srt_text or "procesador" in srt_text

    manifest = styler.generate_json_manifest(chunks)
    assert manifest["version"] == "2.0-KineticVox"
    assert manifest["total_chunks"] == len(chunks)
    assert len(manifest["chunks"][0]["words"]) == 3


def test_modern_hud_overlay_generation(tmp_path):
    """Verify PNG overlay generation with transparent background and crisp graphics."""
    hud_gen = ModernHUDGenerator(resolution="4k")
    shot_mock = {
        "shot_index": 1,
        "shot_id": "SHOT_01_TEST",
        "act": "Acto I: Test",
        "time_window": "00:00 - 00:05",
        "hud_overlay_telemetry": {
            "location": "Gran Sasso Test Lab",
            "telemetry": "TEMP: 10mK | COHERENCE: 99.99%",
            "lower_third": "TEST LOWER THIRD"
        }
    }

    out_file = tmp_path / "hud_test_4k.png"
    img = hud_gen.generate_shot_hud_image(shot_mock, total_shots=24, output_path=out_file)

    assert out_file.exists()
    assert img.size == (3840, 2160)
    assert img.mode == "RGBA"

    # Check that top-left pixel outside UI is fully transparent
    pixel_center = img.getpixel((10, 10))
    assert pixel_center[3] == 0  # Alpha 0 (transparent)


from app.core.orchestration.capabilities import Capability


def test_subtitles_adapter_orchestration(tmp_path):
    """Test full SubtitlesAdapter execution."""
    adapter = SubtitlesAdapter()
    assert adapter.engine_id == "vox_subtitles"

    step = JobStep(
        step_id="step_subtitles_01",
        name="Generar Subtítulos Vox",
        capability=Capability.SUBTITLE_GENERATION,
        engine_id="vox_subtitles",
        provider_id="local_vox_subtitles",
        input_payload={
            "text": "La frontera entre la mente biológica y el cálculo cuántico comienza a desvanecerse.",
            "asr_data": [
                {"word": "La", "start": 0.0, "end": 0.2},
                {"word": "frontera", "start": 0.25, "end": 0.7},
                {"word": "entre", "start": 0.75, "end": 1.0},
                {"word": "la", "start": 1.05, "end": 1.2},
                {"word": "mente", "start": 1.25, "end": 1.6},
                {"word": "biológica", "start": 1.65, "end": 2.2},
                {"word": "y", "start": 2.25, "end": 2.4},
                {"word": "el", "start": 2.45, "end": 2.6},
                {"word": "cálculo", "start": 2.65, "end": 3.1},
                {"word": "cuántico", "start": 3.15, "end": 3.7},
                {"word": "comienza", "start": 3.75, "end": 4.2},
                {"word": "a", "start": 4.25, "end": 4.4},
                {"word": "desvanecerse", "start": 4.45, "end": 5.0}
            ],
            "resolution": "1080p",
            "generate_hud_overlays": False
        }
    )

    context = {"task_dir": str(tmp_path)}
    result = adapter.execute(step, context)

    assert result["status"] == "success"
    assert Path(result["ass_path"]).exists()
    assert Path(result["srt_path"]).exists()
    assert Path(result["json_path"]).exists()
    assert result["total_chunks"] >= 1
    assert result["alignment_rate_pct"] > 90.0


if __name__ == "__main__":
    import tempfile
    print("▶ Running test_token_normalization_and_similarity...")
    test_token_normalization_and_similarity()
    print("  ✓ PASS")

    print("▶ Running test_forced_alignment_purges_hallucinations...")
    test_forced_alignment_purges_hallucinations()
    print("  ✓ PASS")

    print("▶ Running test_kinetic_styler_ass_generation...")
    test_kinetic_styler_ass_generation()
    print("  ✓ PASS")

    with tempfile.TemporaryDirectory() as tmp_dir:
        tmp_p = Path(tmp_dir)
        print("▶ Running test_srt_and_json_manifest_exports...")
        test_srt_and_json_manifest_exports(tmp_p)
        print("  ✓ PASS")

        print("▶ Running test_modern_hud_overlay_generation...")
        test_modern_hud_overlay_generation(tmp_p)
        print("  ✓ PASS")

        print("▶ Running test_subtitles_adapter_orchestration...")
        test_subtitles_adapter_orchestration(tmp_p)
        print("  ✓ PASS")

    print("\n" + "=" * 60)
    print("🎉 ALL 6 COMPREHENSIVE TESTS PASSED WITH 100% SUCCESS!")
    print("=" * 60)

